#!/usr/bin/env zsh

files=(~/.vimrc ~/.tmux.conf ~/.zshrc ~/.bin ~/.config/alacritty)

for file in $files; do
	if [ $(basename "$file") = "alacritty" ]; then
		cp -r $file ~/.dotfiles/.config
	else
		cp -r $file ~/.dotfiles
	fi
done

cd ~/.dotfiles
git add .
vared -p 'Commit message: ' -c message
git commit -m "$message"
branch=$(git branch -r --list | fzf)
print -P '%F{cyan}$branch%f'
git push origin $(basename $branch)
