#!/usr/bin/env zsh
autoload colors
colors

files=(~/.vimrc ~/.zshenv ~/.bashrc ~/.zprofile ~/.cht-languages ~/.cht-command ~/.viebrc ~/.vieb ~/.yabairc ~/.skhdrc ~/.tmux.conf ~/.zshrc ~/.bin ~/.config/alacritty ~/.config/lf ~/vscode-custom-css.css ~/.profile)

for file in $files; do
	if [ $(basename "$file") = "alacritty" ] || [ $(basename "$file") = "lf" ]; then
		cp -r $file ~/.dotfiles/.config
	else
		cp -r $file ~/.dotfiles
	fi
done

cd ~/.dotfiles
git add .
vared -p 'Commit message: ' -c message
git commit -m "$message"
branch=$(git branch -r --list | fzf)
echo $fg[blue]$branch$fg[default]
git push origin $(basename $branch)
