#!/usr/bin/env zsh
autoload colors
colors

files=($(cat ~/.dot-files))

for file in $files; do
	if [[ $file == *.config/* ]]; then
		cp -r $file ~/.dotfiles/.config
	else
		cp -r $file ~/.dotfiles
	fi
done

cd ~/.dotfiles
git add .
vared -p 'Commit message: ' -c message
git commit -m "$message"
branch=$(git branch -r --list | fzf)
echo $fg[blue]$branch$fg[default]
git push origin $(basename $branch)
