#!/usr/bin/env zsh

CURRENT_STATE=$(osascript -e 'tell application "System Events" to tell dock preferences to get autohide menu bar')

if [[ "$CURRENT_STATE" == "true" ]]; then
    osascript -e 'tell application "System Events" to tell dock preferences to set autohide menu bar to false'
else
    osascript -e 'tell application "System Events" to tell dock preferences to set autohide menu bar to true'
fi
