#!/usr/bin/env zsh

FLAG=$1

if [[ -z "$FLAG"  || ("$FLAG" != "off" && "$FLAG" != "on") ]]; then
    echo "Usage: mouse <command> \n<command> : on | off"
    exit 1
fi

if [[ "$FLAG" == "on" ]]; then
    defaults write com.apple.AppleMultitouchTrackpad USBMouseStopsTrackpad 0
    exit 0
fi

if [[ "$FLAG" == "off" ]]; then
    defaults write com.apple.AppleMultitouchTrackpad USBMouseStopsTrackpad 1
    exit 0
fi

