#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find /Users ~/.config  ~/Projects ~ ~/College '/Users/sangitmanandhar/Library/Mobile Documents/com~apple~CloudDocs' '/Volumes/Store' '/Volumes/Store/Projects'  -mindepth 1 -maxdepth 1 -type d 2> /dev/null |  fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t=$selected_name 2>/dev/null; then
	tmux new-session -ds $selected_name -c $PWD
fi

alacritty -e tmux attach -t "$selected_name" &
disown
