[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Retina"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 0

[window.padding]
x = 0
y = 0

[terminal]
